#Set to "socket" in order to use the built-in socket communication system
#Set to "redis" in order to use a Redis server to communicate inter-proxy
communication: socket

#Configuration for a redis connection
redis:
  host: "localhost"
  port: 6379

#Configuration for the socket system
socket-config:
  #What port should we use for the sockets?
  port: 12345
  #How long should we wait before reconnecting a dead socket?
  #(Not currently implemented)
  retry: 3600
  #How long should we wait (multiplied by proxy-id) until we attempt connections?
  #This is useful to have us wait until all proxies are ready before we try and connect.
  connection-delay: 10
  #What is this proxy's ID?
  #This ID is used for connection conflicts, as we try to maintain only one connection between servers
  #It's also used to attempt to decrease the overall amount of sockets and conflicts by delaying (see above)
  proxy-id: 1

#List of proxies to connect to if the socket system is enabled.
#Please note that this also acts as a simple IP-based authentication system, to prevent malicious users from
#connecting and changing data.
servers:
  1:
    #What address can we find this server at?
    address: 127.0.0.1
  2:
    address: 10.0.0.1
    #Declare a custom port for this server.
    port: 44445
  #etc.